graph = {
    'Jurong East': {'Clementi': 2, 'Bukit Batok': 2,},
    'Clementi': {'Jurong East': 2, 'Buona Vista': 4},
    'Buona Vista': {'Clementi': 4, 'Botanic Gardens': 2, 'City Hall': 5},
    'Bukit Batok': {'Jurong East': 2, 'Choa Chu Kang': 3},
    'Botanic Gardens': {'Buona Vista': 2, 'Orchard': 3},
    'Orchard': {'Botanic Gardens': 3, 'City Hall': 2},
    'City Hall': {'Orchard': 2, 'Buona Vista': 5},
    'Choa Chu Kang': {'Bukit Batok': 3, 'Woodlands': 6},
    'Woodlands': {'Choa Chu Kang': 6},
    'Ang Mo Kio': {'Yio Chu Kang': 2, 'Bishan': 3},
    'Bishan': {'Ang Mo Kio': 3, 'Braddell': 2},
    'Braddell': {'Bishan': 2, 'Toa Payoh': 2},
    'Toa Payoh': {'Braddell': 2, 'Novena': 3},
    'Novena': {'Toa Payoh': 3, 'Newton': 2},
    'Newton': {'Novena': 2, 'Orchard': 2},
    'Orchard': {'Newton': 2, 'Somerset': 2},
    'Somerset': {'Orchard': 2, 'Dhoby Ghaut': 2},
    'Dhoby Ghaut': {'Somerset': 2, 'City Hall': 2},
    'City Hall': {'Dhoby Ghaut': 2, 'Raffles Place': 2},
    'Raffles Place': {'City Hall': 2, 'Marina Bay': 2},
    'Marina Bay': {'Raffles Place': 2, 'Marina South Pier': 2},
    'Marina South Pier': {'Marina Bay': 2},
    'Yew Tee': {'Choa Chu Kang': 2, 'Kranji': 3},
    'Kranji': {'Yew Tee': 3, 'Marsiling': 2},
    'Marsiling': {'Kranji': 2, 'Woodlands': 2},
    'Woodlands': {'Marsiling': 2, 'Admiralty': 2},
    'Admiralty': {'Woodlands': 2, 'Sembawang': 3},
    'Sembawang': {'Admiralty': 3, 'Canberra': 2},
    'Canberra': {'Sembawang': 2, 'Yishun': 3},
    'Yishun': {'Canberra': 3, 'Khatib': 2},
    'Khatib': {'Yishun': 2, 'Yio Chu Kang': 3},
    'Yio Chu Kang': {'Khatib': 3, 'Ang Mo Kio': 2},
}